handler: src/onconnect.handle
events:
  - websocket:
      route: $connect

package:
  patterns:
    - ./src/onconnect.js

iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:PutItem
    Resource:
      - Fn::GetAtt: [ConnectionsWebsocketTable, Arn]