handler: src/ondisconnect.handle
events:
  - websocket:
      route: $disconnect

package:
  patterns:
    - ./src/ondisconnect.js

iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:DeleteItem
    Resource:
      - Fn::GetAtt: [ConnectionsWebsocketTable, Arn]      