service: jscoe155-events

frameworkVersion: '3'

custom:
  eventBus: 'jscoe155'
  eventSource: 'moduscreate.jscoe155'
  stackDescription: 'JSCOE-155 - Event component resources'
  stage: ${opt:stage, self:provider.stage}
  tags:
    App: 'jscoe.moduscreate.com'
    Env: ${self:custom.stage}
    OU: 'moduscreate'
    Owner: 'Matthew Warman'
    Issue: 'JSCOE-155'

provider:
  name: aws
  stage: dev
  region: us-east-1
  runtime: nodejs14.x
  memorySize: 128
  timeout: 6
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - events:PutEvents
          Resource:
            - { 'Fn::GetAtt': ['EventBus', 'Arn'] }
  environment:
    EVENTBRIDGE_BUS: ${self:custom.eventBus}
    EVENTBRIDGE_SOURCE: ${self:custom.eventSource}
  logRetentionInDays: 7
  tags: ${self:custom.tags}

functions:
  createEvent:
    handler: src/handlers/createEvent.handle
    events:
      - http:
          path: /events
          method: post

resources:
  Description: ${self:custom.stackDescription}

  Resources:
    EventBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: ${self:custom.eventBus}

    EventArchive:
      Type: AWS::Events::Archive
      Properties:
        ArchiveName: ${self:custom.eventBus}-eventBus-archive
        SourceArn: !GetAtt EventBus.Arn
        EventPattern:
          source:
            - ${self:custom.eventSource}
          detail-type:
            - 'Ballot Submitted'

  Outputs:
    EventBusArn:
      Description: EventBridge Event Bus ARN
      Value:
        'Fn::GetAtt': [EventBus, Arn]
    EventBusName:
      Description: EventBridge Event Bus Name
      Value: !Ref EventBus
