service: jscoe155-books

custom:
  eventBusStack: 'jscoe155-events'
  eventSource: 'moduscreate.jscoe155'
  stage: ${opt:stage, self:provider.stage}
  tags:
    App: 'jscoe.moduscreate.com'
    Env: ${self:custom.stage}
    OU: 'moduscreate'
    Owner: 'Matthew Warman'
    Issue: 'JSCOE-155'

provider:
  name: aws
  stage: dev
  region: us-east-1
  runtime: nodejs14.x
  memorySize: 128
  timeout: 6
  environment:
    EVENTBRIDGE_SOURCE: ${self:custom.eventSource}
    API_BASEURL: ${cf:${self:custom.eventBusStack}-${self:custom.stage}.ServiceEndpoint}
  logRetentionInDays: 7
  tags: ${self:custom.tags}

functions:
  requestHold:
    handler: src/requestHold.handle
    events:
      - eventBridge:
          eventBus: ${cf:${self:custom.eventBusStack}-${self:custom.stage}.EventBusArn}
          pattern:
            source:
              - ${self:custom.eventSource}
            detail-type:
              - 'Hold Requested'
