service: zipper-file-async
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, "dev"}
  environment:
    ${file(./config/${opt:stage, 'dev'}.json)}
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'

functions:
  upload:
    role: UploadRole
    handler: src/index.uploader
    events:
      - http: 
          path: save
          method: post
  zipper:
    role: UploadRole
    handler: src/index.zipper
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ZipFileQueue
              - Arn
          batchSize: 1
          maximumBatchingWindow: 60

plugins:
  - serverless-s3-local
  - serverless-offline
custom:
  FILES_ZIPPED_TABLE: ZIPPED
  s3:
    host: localhost
    directory: /tmp

resources:
  Resources:
    UploadRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: myPolicyName
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
                - Effect: Allow
                  Action:
                    - s3:*
                  Resource:
                    Fn::Join:
                      - ""
                      - - "arn:aws:s3:::modusland"
                        - "/*"
                - Effect: Allow
                  Action:
                    - dynamodb:Query
                    - dynamodb:Scan
                    - dynamodb:GetItem
                    - dynamodb:PutItem
                    - dynamodb:UpdateItem
                    - dynamodb:DeleteItem
                  Resource:
                    - Fn::GetAtt: [ FilesTable, Arn ]
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: modusland
        AccessControl: PublicRead
    ZipFileQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "ZipFile"
    FilesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.FILES_ZIPPED_TABLE}
