version: '3'

services:
  frontend:
    container_name: frontend-dev
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    command: npm run start
    depends_on:
      - "backend1"
      - "backend2"
      - "backend3"
    ports:
      - "3000:3000"
    networks:
     - web
      
  loadbalancer:
    build: ./loadbalancer
    ports:
      - "8080:8080"
    networks:
     - web

  backend1:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: development
    command: npm run start
    container_name: backend1
    # ports:
    #   - "8081:8080"
    networks:
     - web
      
  backend2:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: development
    command: npm run start
    container_name: backend2
    # ports:
    #   - "8082:8080"
    networks:
     - web

  backend3:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: development
    command: npm run start
    container_name: backend3
    # ports:
    #   - "8083:8080"
    networks:
     - web
      
networks:
 web: